---
language: python
python: "2.7"
os: linux
dist: trusty
env:
  - ansible_version="2.0.0.2"
  - ansible_version="2.0.2.0"
  - ansible_version="2.1.3.0"
  - ansible_version="2.2.0.0"

# Use the new container infrastructure
sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

before_install:
  # Install ansible
  - pip install -I "ansible==$ansible_version"
  #install install_nextcloud not using ansible galaxy
  - cd ..
  - wget https://github.com/aalaesar/install_nextcloud/archive/v1.2.1.tar.gz
  - tar -xzf v1.2.1.tar.gz
  - ls
  - cd -

install:

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg
  # Install install_Nexcloud
  #- ansible-galaxy install aalaesar.install_nextcloud
  # Install Nexcloud 9
  - ansible-playbook tests/nc_init.yml -i tests/inventory

script:
  # Test update script
  - php tests/nc_check_versions_test.php

  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Upgrade nextcloud 9 to 10
  - ansible-playbook tests/test.yml -i tests/inventory -v

  # test login pages
  - curl -i -s --insecure --data "user=ncadmin&password=" https://localhost/index.php/login | egrep -q "Location:.*/apps/files/"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
